### ISSUE TITLE
Examples include outdated property

### ISSUE THREAD

**Issue by EnturWilhelm** [entur/helm-charts#133]
Numerous examples include the outdated (or deprecated?) property `common.configmap.toEnv`.

See e.g. https://github.com/entur/helm-charts/blob/main/examples/common/simple-app/values-kub-ent-dev.yaml

**Comment by AlexanderBrevig** [comment]
Thanks! I hope to get an overhaul of the examples done soon. If you want, feel free to make a PR : ]

**Comment by AlexanderBrevig** [comment]
Fixed in PR above
