### ISSUE TITLE
maxReplicas must be set to enable custom hpa

### ISSUE THREAD

**Issue by elgbar** [entur/helm-charts#134]
When using a custom hpa spec, either `.Values.deployment.maxReplicas` or `.Values.container.maxReplicas` must be set to allow us to use `.Values.hpa.spec`.

`maxReplicas` is not used when using a custom hpa spec.

**Suggestion for a solution**

Check if `.Values.hpa.spec` is defined when deciding whether hpa should be created.

**Comment by elgbar** [comment]
@AlexanderBrevig Blir dette sett på?

**Comment by elgbar** [comment]
bump :)

**Comment by AlexanderBrevig** [comment]
Unable to reproduce, unless you want HPA in dev/tst?

The tests pass without setting `maxReplicas`.
https://github.com/entur/helm-charts/blob/b1624aef0a3c31ae7895c2281951f393912a4470/charts/common/tests/hpa_test.yaml#L91-L108

Here's the current rule:
https://github.com/entur/helm-charts/blob/b1624aef0a3c31ae7895c2281951f393912a4470/charts/common/templates/hpa.yaml#L9-L13

If you want to use custom HPA in dev or tst then that would match your report. I guess we could check for `hpa.spec` and enable if seen, but that would suddenly create some HPAs in dev and tst which may not be wanted.

Thoughts?

**Comment by Glenn-Terjesen** [comment]
fixing this today : @elgbar
