### ISSUE TITLE
Replace grpc exec-probes with Kubernetes built-in (once stable)

### ISSUE THREAD

**Issue by kagkarlsson** [entur/helm-charts#35]
We currently use `exec` probes to healthcheck grpc-applications. Kubernetes is getting native support for these healthchecks, and we should migrate to these once stable.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe

```
FEATURE STATE: Kubernetes v1.24 [beta]
```

**Comment by Chr1stian** [comment]
Soon^TM!

**Comment by Chr1stian** [comment]
Ready to roll? 🤞

**Comment by AlexanderBrevig** [comment]
Noen tanker om hvordan vi skal gjøre denne overgangen @Chr1stian? Så ikke noen plutselig blir overrasket over et chart som ikke funker?
Tror jeg får tid ILA uken til å fikse denne, endelig :)

**Comment by Chr1stian** [comment]
Hmm, kanskje det på en eller annen måte går an å støtte begge deler? Så kan de som vet, vite, og fjerne det fra sine Docker-images, men det fungerer fortsatt for de som ikke vet? 🤷
