### ISSUE TITLE
CI should validate generated YAML against K8s api

### ISSUE THREAD

**Issue by kagkarlsson** [entur/helm-charts#61]
Use a (strict) validator for the generated yaml to verify that the generated yaml is correct. This help early detection of for example the misformed CronJob 

**Example validators**
* https://github.com/yannh/kubeconform
* https://github.com/instrumenta/kubeval. (not maintained)

**Example**
```
helm template charts/common -f example/values-minimal.yaml | kubeconform --strict
stdin - Deployment release-name is invalid: For field spec.strategy: Additional property maxSurge is not allowed
```

**Comment by AlexanderBrevig** [comment]
We already check both versions and validity with `kind` cluster https://github.com/entur/gh-workflows/blob/main/.github/workflows/pr-tests-helm.yml#L112.

The issue here is that we are missing a ci test for the cron job. Refer to #42
