### ISSUE TITLE
CPU-request formatting issue

### ISSUE THREAD

**Issue by lassetyr** [entur/helm-charts#76]
Minor issue when specifying request-cpu:

https://github.com/entur/helm-charts/blob/4d6566160ee90dd2fbf0959112a977f98a1df4e1/charts/common/values.yaml#L123-L125

It is documented that the format should be e.g. `0.2`, but in the resulting deployment.yaml, it is written as `200m`. 
This may cause a bit confusion since you can't reuse a value from an existing kubernetes deployment.yaml in the helm-chart to produce the exact same result.

E.g. if you specify `0.2`, you will get `200m`, but if you specify `200m`, you will get `0`.

Could this value possibly be inserted in the deployment.yaml as-is without any conversion?
Ref. https://github.com/entur/helm-charts/blob/31930d0aa5d02da35a5e3becb3151eb161a473d6/charts/common/templates/_helpers.tpl#L48

**Comment by AlexanderBrevig** [comment]
The reason for this quirk is that we wanted to provide a sane default cpu and memory limit (if none are provided). 

I wanted to stay away from unit conversions, and landed on using the default values from k8s API. 

Then, as you can see, there was a version mismatch and we have no way to multiply floats - hence the hacky multiplication.

I am absolutely open to the idea of reverting to "free text" and at the same time set limit = request, but this will probably lead to _a lot_ of application not stating.

**Comment by AlexanderBrevig** [comment]
Refer to #5
